// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_WINDOWS_API_KEY']!,
    appId: dotenv.env['WEB_APP_ID']!,
    messagingSenderId: '391687245600',
    projectId: 'building-report-system',
    authDomain: 'building-report-system.firebaseapp.com',
    storageBucket: 'building-report-system.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: dotenv.env['ANDROID_APP_ID']!,
    messagingSenderId: '391687245600',
    projectId: 'building-report-system',
    storageBucket: 'building-report-system.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_MACOS_API_KEY']!,
    appId: dotenv.env['IOS_MACOS_APP_ID']!,
    messagingSenderId: '391687245600',
    projectId: 'building-report-system',
    storageBucket: 'building-report-system.appspot.com',
    iosBundleId: 'com.example.buildingReportSystem',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['IOS_MACOS_API_KEY']!,
    appId: dotenv.env['IOS_MACOS_APP_ID']!,
    messagingSenderId: '391687245600',
    projectId: 'building-report-system',
    storageBucket: 'building-report-system.appspot.com',
    iosBundleId: 'com.example.buildingReportSystem',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WEB_WINDOWS_API_KEY']!,
    appId: dotenv.env['WINDOWS_APP_ID']!,
    messagingSenderId: '391687245600',
    projectId: 'building-report-system',
    authDomain: 'building-report-system.firebaseapp.com',
    storageBucket: 'building-report-system.appspot.com',
  );
}
